"bashrc" = ".bashrc"
"starship.toml" = ".config/starship.toml"
"gitconfig" = ".gitconfig"
"nvim" = ".config/nvim"
"gdbinit" = ".gdbinit"
"dircolors" = ".dircolors"
"wezterm" = ".config/wezterm"
"ghostty" = ".config/ghostty"
"helix" = ".config/helix"
"zshrc" = ".zshrc"
"editorconfig" = ".editorconfig"

[home]
"ssh-config" = ".ssh/config"
