# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[git_branch]
disabled = false
truncation_length = 8
ignore_branches = ["master", "main"]
only_attached = true

[git_state]
disabled = false

[git_metrics]
disabled = true

[git_status]
disabled = true

