-- Disabled plugins that LazyVim includes by default
return {
  { "folke/flash.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "echasnovski/mini.icons", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "nvim-treesitter", enabled = false },
  { "nvim-treesitter-textobjects", enabled = false },
  { "nvim-ts-autotag", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "JoosepAlviste/nvim-ts-context-commentstring", enabled = false },
  { "folke/ts-comments.nvim", enabled = false },
  { "hrsh7th/cmp-path", enabled = false },
  { "nvim-tree/nvim-web-devicons", enabled = false },
}
