-- Disabled plugins that LazyVim includes by default
return {
  { "RRethy/vim-illuminate", enabled = false },
  { "SmiteshP/nvim-navic", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "echanovski/mini.pairs", enabled = false },
  { "L3MON4D3/LuaSnip", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "hrsh7th/cmp-nvim-lsp", enabled = false },
  { "echasnovski/mini.bufremove", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "nvim-treesitter/nvim-treesitter", enabled = false },
  { "windwp/nvim-ts-autotag", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "hrsh7th/nvim-cmp", enabled = false },
  { "echanovski/mini.surround", enabled = false },
}
